// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zguyatyrbdtnpaeqxdda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndXlhdHlyYmR0bnBhZXF4ZGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjEwNTYsImV4cCI6MjA3MjEzNzA1Nn0.Uvn9asGHLdyA6hP5YjnYQy2j4-ktgeqlSFmPbTDMwTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});